%% FILENAME
function FEATURE=config_feature()
FEATURE.R_RIPID=1;
FEATURE.R_ECGID=2;
FEATURE.R_RIPECGID=3;
FEATURE.R_ACLID=4;
FEATURE.P_ACLID=5;

FEATURE.R_RIP.INSPDURATION=1;     FEATURE.R_RIP.NAME{1}='Inspiration Duration';
FEATURE.R_RIP.EXPRDURATION=2;     FEATURE.R_RIP.NAME{2}='Expiration Duration';
FEATURE.R_RIP.RESPDURATION=3;     FEATURE.R_RIP.NAME{3}='Respiration Duration';
FEATURE.R_RIP.IERATIO=4;          FEATURE.R_RIP.NAME{4}='IE Ratio';
FEATURE.R_RIP.STRETCH=5;          FEATURE.R_RIP.NAME{5}='Stretch';

FEATURE.R_RIP.EXPRDURATIONRATIO_5=6;FEATURE.R_RIP.NAME{6}='Expiration Duration Ratio 5';

FEATURE.R_RIP.FDBINSP=7;      FEATURE.R_RIP.NAME{7}='First Difference (Backward) for Inspiration Duration';
FEATURE.R_RIP.FDFINSP=8;      FEATURE.R_RIP.NAME{8}='First Difference (Forward) for Inspiration Duration';
FEATURE.R_RIP.FDBEXPR=9;     FEATURE.R_RIP.NAME{9}='First Difference (Backward) for Expiration Duration';
FEATURE.R_RIP.FDFEXPR=10;     FEATURE.R_RIP.NAME{10}='First Difference (Forward) for Expiration Duration';
FEATURE.R_RIP.FDBSTRETCH=11;  FEATURE.R_RIP.NAME{11}='First Difference (Backward) for Stretch';
FEATURE.R_RIP.FDFSTRETCH=12;  FEATURE.R_RIP.NAME{12}='First Difference (Forward) for Stretch';

FEATURE.R_RIP.STRETCHRATIO_5=13;  FEATURE.R_RIP.NAME{13}='Stretch Ratio in 5 cycles';
FEATURE.R_RIP.STRETCHRATIO=14;    FEATURE.R_RIP.NAME{14}='Stretch Ratio';
FEATURE.R_RIP.MXMDSTRCHRATIO=15;  FEATURE.R_RIP.NAME{15}='mxmd_stretch_ratio';
FEATURE.R_RIP.STRETCHUP=16;       FEATURE.R_RIP.NAME{16}='Stretch Up';
FEATURE.R_RIP.STRETCHDOWN=17;     FEATURE.R_RIP.NAME{17}='Stretch Down';

FEATURE.R_RIP.FDBRESP=18;         FEATURE.R_RIP.NAME{18}='First Difference (Backward) for Respiration Duration';
FEATURE.R_RIP.FDFRESP=19;         FEATURE.R_RIP.NAME{19}='First Difference (Forward) for Respiration Duration';

FEATURE.R_RIP.BREATHRATE=20;                       FEATURE.R_RIP.NAME{20}='Breath Rate';
FEATURE.R_RIP.MINUTEVENT=21;                       FEATURE.R_RIP.NAME{21}='Minute Ventilation';

FEATURE.R_RIP.INSPDURQUARTDEV=22;                  FEATURE.R_RIP.NAME{22}='Quartile Deviation of Inspiration Duration';
FEATURE.R_RIP.INSPDURMEAN=23;                      FEATURE.R_RIP.NAME{23}='Mean of Inspiration Duration';
FEATURE.R_RIP.INSPDURMEDIAN=24;                    FEATURE.R_RIP.NAME{24}='Median of Inspiration Duration';
FEATURE.R_RIP.INSPDUR80PERCENT=25;                    FEATURE.R_RIP.NAME{25}='80th Percentile of Inspiration Duration';

FEATURE.R_RIP.EXPRDURQUARTDEV=26;                  FEATURE.R_RIP.NAME{26}='Quartile Deviation of Expiration Duration';
FEATURE.R_RIP.EXPRDURMEAN=27;                  FEATURE.R_RIP.NAME{27}='Mean of Expiration Duration';
FEATURE.R_RIP.EXPRDURMEDIAN=28;                  FEATURE.R_RIP.NAME{28}='Median of Expiration Duration';
FEATURE.R_RIP.EXPRDUR80PERCENT=29;                  FEATURE.R_RIP.NAME{29}='80th Percentile of Expiration Duration';

FEATURE.R_RIP.RESPDURQUARTDEV=30;                  FEATURE.R_RIP.NAME{30}='Quartile Deviation of Respiration Duration';
FEATURE.R_RIP.RESPDURMEAN=31;                  FEATURE.R_RIP.NAME{31}='Mean of Respiration Duration';
FEATURE.R_RIP.RESPDURMEDIAN=32;                  FEATURE.R_RIP.NAME{32}='Median of Respiration Duration';
FEATURE.R_RIP.RESPDUR80PERCENT=33;                  FEATURE.R_RIP.NAME{33}='80th Percentile of Respiration Duration';

FEATURE.R_RIP.IERATIOQUARTDEV=34;                  FEATURE.R_RIP.NAME{34}='Quartile Deviation of IE Ratio';
FEATURE.R_RIP.IERATIOMEAN=35;                    FEATURE.R_RIP.NAME{35}='Mean of IE Ratio';
FEATURE.R_RIP.IERATIOMEDIAN=36;                  FEATURE.R_RIP.NAME{36}='Median of IE Ratio';
FEATURE.R_RIP.IERATIO80PERCENT=37;                  FEATURE.R_RIP.NAME{37}='80th Percentile of IE Ratio';

FEATURE.R_RIP.STRETCHQUARTDEV=38;                  FEATURE.R_RIP.NAME{38}='Quartile Deviation of Stretch';
FEATURE.R_RIP.STRETCHMEAN=39;                    FEATURE.R_RIP.NAME{39}='Mean of Stretch';
FEATURE.R_RIP.STRETCHMEDIAN=40;                  FEATURE.R_RIP.NAME{40}='Median of Stretch';
FEATURE.R_RIP.STRETCH80PERCENT=41;                  FEATURE.R_RIP.NAME{41}='80th Percentile of Stretch';

%% Features for ECG
FEATURE.R_ECG.RR=1;       FEATURE.R_ECG.NAME{1}='RR Interval';
FEATURE.R_ECG.VRVL=2;     FEATURE.R_ECG.NAME{2}='Varience of RR Interval';
FEATURE.R_ECG.LFHF=3;     FEATURE.R_ECG.NAME{3}='Low High Frequency Ratio';
FEATURE.R_ECG.HRP1=4;     FEATURE.R_ECG.NAME{4}='High Frequency Energy';
FEATURE.R_ECG.HRP2=5;          FEATURE.R_ECG.NAME{5}='Medium Frequency Energy';
FEATURE.R_ECG.HRP3=6;          FEATURE.R_ECG.NAME{6}='Low Frequency Energy';

FEATURE.R_ECG.RRMN=7;		FEATURE.R_ECG.NAME{7}='Mean of RR Interval';

FEATURE.R_ECG.RRMD=8;      FEATURE.R_ECG.NAME{8}='Median of RR Interval';
FEATURE.R_ECG.RRQD=9;      FEATURE.R_ECG.NAME{9}='Quartile Deviation of RR interval';
FEATURE.R_ECG.RR80=10;     FEATURE.R_ECG.NAME{10}='80th Percentile of RR Interval';
FEATURE.R_ECG.RR20=11;     FEATURE.R_ECG.NAME{11}='20th Percentile of RR Interval';
FEATURE.R_ECG.RRCT=12;     FEATURE.R_ECG.NAME{12}='Heart Rate';

%% Features for RIP & ECG
FEATURE.R_RIPECG.RSA=1;             FEATURE.R_RIPECG.NAME{1}='RSA';
FEATURE.R_RIPECG.RSAQUARTDEV=43;                             FEATURE.R_RIPECG.NAME{43}='Quartile Deviation of RSA';
FEATURE.R_RIPECG.RSAMEAN=44;                             FEATURE.R_RIPECG.NAME{44}='Mean of RSA';
FEATURE.R_RIPECG.RSAMEDIAN=45;                             FEATURE.R_RIPECG.NAME{45}='Median of RSA';
FEATURE.R_RIPECG.RSA80PERCENT=46;                             FEATURE.R_RIPECG.NAME{46}='80th Percentile of RSA';

%{
%% Accelerometer Feature (Chest Band)
FEATURE.R_ACL.MEANX=1;     FEATURE.R_ACL.NAME{1}='Mean of X';
FEATURE.R_ACL.MEDIANX=2;     FEATURE.R_ACL.NAME{2}='Median of X';
FEATURE.R_ACL.VARIANCEX=3;     FEATURE.R_ACL.NAME{3}='Variance of X';
FEATURE.R_ACL.STDDEVX=4;          FEATURE.R_ACL.NAME{4}='Standard Deviation of X';
FEATURE.R_ACL.AVGFDX=5;          FEATURE.R_ACL.NAME{5}='Average of First Difference Difference of X';

FEATURE.R_ACL.MEANY=6;     FEATURE.R_ACL.NAME{6}='Mean of Y';
FEATURE.R_ACL.MEDIANY=7;     FEATURE.R_ACL.NAME{7}='Median of Y';
FEATURE.R_ACL.VARIANCEY=8;     FEATURE.R_ACL.NAME{8}='Variance of Y';
FEATURE.R_ACL.STDDEVY=9;          FEATURE.R_ACL.NAME{9}='Standard deviation of Y';
FEATURE.R_ACL.AVGFDY=10;          FEATURE.R_ACL.NAME{10}='Average of First Difference of Y';

FEATURE.R_ACL.MEANZ=11;     FEATURE.R_ACL.NAME{11}='Mean of Z';
FEATURE.R_ACL.MEDIANZ=12;     FEATURE.R_ACL.NAME{12}='Median of Z';
FEATURE.R_ACL.VARIANCEZ=13;     FEATURE.R_ACL.NAME{13}='Variance of Z';
FEATURE.R_ACL.STDDEVZ=14;          FEATURE.R_ACL.NAME{14}='Standard Deviation of Z';
FEATURE.R_ACL.AVGFDZ=15;          FEATURE.R_ACL.NAME{15}='Average of First Difference of Z';

FEATURE.R_ACL.AVGDIFFXY=16;     FEATURE.R_ACL.NAME{16}='Average Difference between X & Y';
FEATURE.R_ACL.AVGDIFFYZ=17;     FEATURE.R_ACL.NAME{17}='Average Difference between Y & Z';
FEATURE.R_ACL.AVGDIFFZX=18;     FEATURE.R_ACL.NAME{18}='Average Difference between Z & X';

FEATURE.R_ACL.MEANCROSSINGX=19;     FEATURE.R_ACL.NAME{19}='Mean Crossing of X';
FEATURE.R_ACL.MEANCROSSINGY=20;     FEATURE.R_ACL.NAME{20}='Mean Crossing of Y';
FEATURE.R_ACL.MEANCROSSINGZ=21;     FEATURE.R_ACL.NAME{21}='Mean Crossing of Z';

FEATURE.R_ACL.AVGRATIOXY=22;     FEATURE.R_ACL.NAME{22}='Average Ratio of XY';
FEATURE.R_ACL.AVGRATIOYZ=23;     FEATURE.R_ACL.NAME{23}='Average Ratio of YZ';
FEATURE.R_ACL.AVGRATIOZX=24;     FEATURE.R_ACL.NAME{24}='Average Ratio of ZX';

FEATURE.R_ACL.AVGENERGY=25;          FEATURE.R_ACL.NAME{25}='Average Energy';
FEATURE.R_ACL.MEDIANENERGY=26;          FEATURE.R_ACL.NAME{26}='Median Energy';
FEATURE.R_ACL.VARIANCEENERGY=27;          FEATURE.R_ACL.NAME{27}='Variance of Energy';
FEATURE.R_ACL.STDDEVENERGY=28;          FEATURE.R_ACL.NAME{28}='Standard Deviation of Energy';
FEATURE.R_ACL.AVGFDENERGY=29;          FEATURE.R_ACL.NAME{29}='Average of Forward Difference of Energy';
FEATURE.R_ACL.RANGEENERGY=30;          FEATURE.R_ACL.NAME{30}='Range Energy';
FEATURE.R_ACL.MEANCROSSINGENERGY=31;          FEATURE.R_ACL.NAME{31}='Mean Crossing of Energy';

FEATURE.R_ACL.RANGEX=32;     FEATURE.R_ACL.NAME{32}='Range of X';
FEATURE.R_ACL.RANGEY=33;     FEATURE.R_ACL.NAME{33}='Range of Y';
FEATURE.R_ACL.RANGEZ=34;     FEATURE.R_ACL.NAME{34}='Range of Z';
%}

%% CHEST BAND ACCELEROMETER
FEATURE.R_ACL=4;
FEATURE.FREQUENCYBAND=5;   %FREQUENCY BAND: LOW=1-5Hz HIGH IS >5Hz
FEATURE.R_ACL.MAXOFMEAN=1;     FEATURE.R_ACL.NAME{1}='MAX_MEAN';
FEATURE.R_ACL.MEANOFMEAN=2;     FEATURE.R_ACL.NAME{2}='MEAN_MEAN';
FEATURE.R_ACL.MINOFMEAN=3;     FEATURE.R_ACL.NAME{3}='MIN_MEAN';

FEATURE.R_ACL.MAXOFMIN=4;          FEATURE.R_ACL.NAME{4}='MAX_MIN';
FEATURE.R_ACL.MINOFMAX=5;          FEATURE.R_ACL.NAME{5}='MIN_MAX';

FEATURE.R_ACL.MINOFMIN=6;     FEATURE.R_ACL.NAME{6}='MIN_MIN';
FEATURE.R_ACL.MAXOFMAX=7;     FEATURE.R_ACL.NAME{7}='MAX_MAX';

FEATURE.R_ACL.MAXOFRANGE=8;     FEATURE.R_ACL.NAME{8}='MAX_RANGE';
FEATURE.R_ACL.MINOFRANGE=9;          FEATURE.R_ACL.NAME{9}='MIN_RANGE';
FEATURE.R_ACL.MAXOFSTD=10;          FEATURE.R_ACL.NAME{10}='MAX_STD';

FEATURE.R_ACL.MINOFSTD=11;     FEATURE.R_ACL.NAME{11}='MIN_STD';
FEATURE.R_ACL.MEANOFSTD=12;     FEATURE.R_ACL.NAME{12}='MEAN_STD';

FEATURE.R_ACL.MINOFMED=13;     FEATURE.R_ACL.NAME{13}='MIN_MED';
FEATURE.R_ACL.MAXOFMED=14;          FEATURE.R_ACL.NAME{14}='MAX_MED';
FEATURE.R_ACL.MEDOFMED=15;          FEATURE.R_ACL.NAME{15}='MED_MED';

FEATURE.R_ACL.MAXFD=16;     FEATURE.R_ACL.NAME{16}='MAX_FD';
FEATURE.R_ACL.MINFD=17;     FEATURE.R_ACL.NAME{17}='MIN_FD';
FEATURE.R_ACL.MEANFD=18;     FEATURE.R_ACL.NAME{18}='MEAN_FD';

FEATURE.R_ACL.MAXCROSSING=19;     FEATURE.R_ACL.NAME{19}='MAX_OF_MEANCROSSINGS';
FEATURE.R_ACL.MEANCROSSING=20;     FEATURE.R_ACL.NAME{20}='MEAN_OF_MEANCROSSINGS';
FEATURE.R_ACL.MINCROSSING=21;     FEATURE.R_ACL.NAME{21}='MIN_OF_MEANCROSSINGS';

FEATURE.R_ACL.TOTALENERGY=22;     FEATURE.R_ACL.NAME{22}='TOTAL_ENERGY';
FEATURE.R_ACL.MAXSTDENERGY=23;     FEATURE.R_ACL.NAME{23}='MAX_OF_STD_ENERGY';
FEATURE.R_ACL.MEANSTDENERGY=24;     FEATURE.R_ACL.NAME{24}='MEAN_OF_STD_ENERGY';

FEATURE.R_ACL.AVGENERGY=25;          FEATURE.R_ACL.NAME{25}='AVERAGE_ENERGY';

FEATURE.R_ACL.MINSTDENERGY=26;     FEATURE.R_ACL.NAME{26}='MIN_OF_STD_ENERGY';
FEATURE.R_ACL.MAXENERGYLF=27;     FEATURE.R_ACL.NAME{27}='MAX_ENERGY_LF';
FEATURE.R_ACL.MINENERGYLF=28;     FEATURE.R_ACL.NAME{28}='MIN_ENERGY_LF';
FEATURE.R_ACL.MEDIANENERGYLF=29;  FEATURE.R_ACL.NAME{29}='MEDIAN_ENERGY_LF';

FEATURE.R_ACL.STDEVMAGNITUDE=30; FEATURE.R_ACL.NAME{30}='STDEV_MAGNITUDE';

FEATURE.R_ACL.MAXENERGYHF=31; FEATURE.R_ACL.NAME{31}='MAX_ENERGY_HF';
FEATURE.R_ACL.MINENERGYHF=32; FEATURE.R_ACL.NAME{32}='MIN_ENERGY_HF';
FEATURE.R_ACL.MEDIANENERGYHF=33; FEATURE.R_ACL.NAME{33}='MEDIAN_ENERGY_HF';

FEATURE.R_ACL.MAXOFMEDIANENERGY=34; FEATURE.R_ACL.NAME{34}='MAX_OF_MEDIAN_ENERGY';
FEATURE.R_ACL.MINOFMEDIANENERGY=35; FEATURE.R_ACL.NAME{35}='MIN_OF_MEDIAN_ENERGY';
FEATURE.R_ACL.MEANOFMEDIANENERGY=36; FEATURE.R_ACL.NAME{36}='MEAN_OF_MEDIAN_ENERGY';


FEATURE.R_ACL.TOTALENERGYLF=37; FEATURE.R_ACL.NAME{37}='TOTAL_ENERGY_LF';
FEATURE.R_ACL.TOTALENERGYHF=38; FEATURE.R_ACL.NAME{38}='TOTAL_ENERGY_HF';

FEATURE.R_ACL.MAGNITUDEFFTONEHZ=39; FEATURE.R_ACL.NAME{39}='SUM_MAGNITUDE_OF_DCCOMPONENT_1HZ_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTTWOHZ=40; FEATURE.R_ACL.NAME{40}='SUM_MAGNITUDE_OF_DCCOMPONENT_2HZ_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTTHREEHZ=41; FEATURE.R_ACL.NAME{41}='SUM_MAGNITUDE_OF_DCCOMPONENT_3HZ_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTFOURHZ=42; FEATURE.R_ACL.NAME{42}='SUM_MAGNITUDE_OF_DCCOMPONENT_4HZ_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTFIVEHZ=43;  FEATURE.R_ACL.NAME{43}='SUM_MAGNITUDE_OF_DCCOMPONENT_5HZ_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTHF=44;  FEATURE.R_ACL.NAME{44}='SUM_MAGNITUDE_OF_DCCOMPONENT_HIGH_FREQ';
FEATURE.R_ACL.MAGNITUDEFFTLF=45;  FEATURE.R_ACL.NAME{45}='SUM_MAGNITUDE_OF_DCCOMPONENT_LOW_FREQ';

FEATURE.R_ACL.MAXMINVARRATIO=46;  FEATURE.R_ACL.NAME{46}='RATIO_OF_MAX_VAR_MIN_VAR_AXIS';
FEATURE.R_ACL.MAXMEANVARRATIO=47;  FEATURE.R_ACL.NAME{47}='RATIO_OF_MAX_VAR_MEAN_VAR_AXIS';
FEATURE.R_ACL.MAXMEDIANVARRATIO=48;  FEATURE.R_ACL.NAME{48}='RATIO_OF_MAX_VAR_MEDIAN_VAR_AXIS';

FEATURE.R_ACL.MAXVAR=49;      FEATURE.R_ACL.NAME{49}='MAX_VARIANCE_OVER_3AXIS';
FEATURE.R_ACL.MINVAR=50;      FEATURE.R_ACL.NAME{50}='MIN_VARIANCE_OVER_3AXIS';
FEATURE.R_ACL.MEANVAR=51;     FEATURE.R_ACL.NAME{51}='MEAN_VARIANCE_OVER_3AXIS';

FEATURE.R_ACL.AVGMAGNITUDE=52; FEATURE.R_ACL.NAME{52}='AVG_MAGNITUDE';

%FEATURE.R_ACL.AUTOCORRX=58;   FEATURE.CHESTACCE.NAME{58}='AUTOCORRELATION_X';
%FEATURE.R_ACL.AUTOCORRY=59;    FEATURE.R_ACL.NAME{59}='AUTOCORRELATION_Y';
%FEATURE.R_ACL.AUTOCORRZ=60;    FEATURE.R_ACL.NAME{60}='AUTOCORRELATION_Z';

FEATURE.R_ACL.FEATURENO=52;

%% PHONE ACCELEROMETER
FEATURE.P_ACL=5;
FEATURE.FREQUENCYBAND=5;   %FREQUENCY BAND: LOW=1-5Hz HIGH IS >5Hz
FEATURE.P_ACL.MAXOFMEAN=1;     FEATURE.P_ACL.NAME{1}='MAX_MEAN';
FEATURE.P_ACL.MEANOFMEAN=2;     FEATURE.P_ACL.NAME{2}='MEAN_MEAN';
FEATURE.P_ACL.MINOFMEAN=3;     FEATURE.P_ACL.NAME{3}='MIN_MEAN';

FEATURE.P_ACL.MAXOFMIN=4;          FEATURE.P_ACL.NAME{4}='MAX_MIN';
FEATURE.P_ACL.MINOFMAX=5;          FEATURE.P_ACL.NAME{5}='MIN_MAX';

FEATURE.P_ACL.MINOFMIN=6;     FEATURE.P_ACL.NAME{6}='MIN_MIN';
FEATURE.P_ACL.MAXOFMAX=7;     FEATURE.P_ACL.NAME{7}='MAX_MAX';

FEATURE.P_ACL.MAXOFRANGE=8;     FEATURE.P_ACL.NAME{8}='MAX_RANGE';
FEATURE.P_ACL.MINOFRANGE=9;          FEATURE.P_ACL.NAME{9}='MIN_RANGE';
FEATURE.P_ACL.MAXOFSTD=10;          FEATURE.P_ACL.NAME{10}='MAX_STD';

FEATURE.P_ACL.MINOFSTD=11;     FEATURE.P_ACL.NAME{11}='MIN_STD';
FEATURE.P_ACL.MEANOFSTD=12;     FEATURE.P_ACL.NAME{12}='MEAN_STD';

FEATURE.P_ACL.MINOFMED=13;     FEATURE.P_ACL.NAME{13}='MIN_MED';
FEATURE.P_ACL.MAXOFMED=14;          FEATURE.P_ACL.NAME{14}='MAX_MED';
FEATURE.P_ACL.MEDOFMED=15;          FEATURE.P_ACL.NAME{15}='MED_MED';

FEATURE.P_ACL.MAXFD=16;     FEATURE.P_ACL.NAME{16}='MAX_FD';
FEATURE.P_ACL.MINFD=17;     FEATURE.P_ACL.NAME{17}='MIN_FD';
FEATURE.P_ACL.MEANFD=18;     FEATURE.P_ACL.NAME{18}='MEAN_FD';

FEATURE.P_ACL.MAXCROSSING=19;     FEATURE.P_ACL.NAME{19}='MAX_OF_MEANCROSSINGS';
FEATURE.P_ACL.MEANCROSSING=20;     FEATURE.P_ACL.NAME{20}='MEAN_OF_MEANCROSSINGS';
FEATURE.P_ACL.MINCROSSING=21;     FEATURE.P_ACL.NAME{21}='MIN_OF_MEANCROSSINGS';

FEATURE.P_ACL.TOTALENERGY=22;     FEATURE.P_ACL.NAME{22}='TOTAL_ENERGY';
FEATURE.P_ACL.MAXSTDENERGY=23;     FEATURE.P_ACL.NAME{23}='MAX_OF_STD_ENERGY';
FEATURE.P_ACL.MEANSTDENERGY=24;     FEATURE.P_ACL.NAME{24}='MEAN_OF_STD_ENERGY';

FEATURE.P_ACL.AVGENERGY=25;          FEATURE.P_ACL.NAME{25}='AVERAGE_ENERGY';

FEATURE.P_ACL.MINSTDENERGY=26;     FEATURE.P_ACL.NAME{26}='MIN_OF_STD_ENERGY';
FEATURE.P_ACL.MAXENERGYLF=27;     FEATURE.P_ACL.NAME{27}='MAX_ENERGY_LF';
FEATURE.P_ACL.MINENERGYLF=28;     FEATURE.P_ACL.NAME{28}='MIN_ENERGY_LF';
FEATURE.P_ACL.MEDIANENERGYLF=29;  FEATURE.P_ACL.NAME{29}='MEDIAN_ENERGY_LF';

FEATURE.P_ACL.STDEVMAGNITUDE=30; FEATURE.P_ACL.NAME{30}='STDEV_MAGNITUDE';

FEATURE.P_ACL.MAXENERGYHF=31; FEATURE.P_ACL.NAME{31}='MAX_ENERGY_HF';
FEATURE.P_ACL.MINENERGYHF=32; FEATURE.P_ACL.NAME{32}='MIN_ENERGY_HF';
FEATURE.P_ACL.MEDIANENERGYHF=33; FEATURE.P_ACL.NAME{33}='MEDIAN_ENERGY_HF';

FEATURE.P_ACL.MAXOFMEDIANENERGY=34; FEATURE.P_ACL.NAME{34}='MAX_OF_MEDIAN_ENERGY';
FEATURE.P_ACL.MINOFMEDIANENERGY=35; FEATURE.P_ACL.NAME{35}='MIN_OF_MEDIAN_ENERGY';
FEATURE.P_ACL.MEANOFMEDIANENERGY=36; FEATURE.P_ACL.NAME{36}='MEAN_OF_MEDIAN_ENERGY';


FEATURE.P_ACL.TOTALENERGYLF=37; FEATURE.P_ACL.NAME{37}='TOTAL_ENERGY_LF';
FEATURE.P_ACL.TOTALENERGYHF=38; FEATURE.P_ACL.NAME{38}='TOTAL_ENERGY_HF';

FEATURE.P_ACL.MAGNITUDEFFTONEHZ=39; FEATURE.P_ACL.NAME{39}='SUM_MAGNITUDE_OF_DCCOMPONENT_1HZ_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTTWOHZ=40; FEATURE.P_ACL.NAME{40}='SUM_MAGNITUDE_OF_DCCOMPONENT_2HZ_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTTHREEHZ=41; FEATURE.P_ACL.NAME{41}='SUM_MAGNITUDE_OF_DCCOMPONENT_3HZ_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTFOURHZ=42; FEATURE.P_ACL.NAME{42}='SUM_MAGNITUDE_OF_DCCOMPONENT_4HZ_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTFIVEHZ=43;  FEATURE.P_ACL.NAME{43}='SUM_MAGNITUDE_OF_DCCOMPONENT_5HZ_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTHF=44;  FEATURE.P_ACL.NAME{44}='SUM_MAGNITUDE_OF_DCCOMPONENT_HIGH_FREQ';
FEATURE.P_ACL.MAGNITUDEFFTLF=45;  FEATURE.P_ACL.NAME{45}='SUM_MAGNITUDE_OF_DCCOMPONENT_LOW_FREQ';

FEATURE.P_ACL.MAXMINVARRATIO=46;  FEATURE.P_ACL.NAME{46}='RATIO_OF_MAX_VAR_MIN_VAR_AXIS';
FEATURE.P_ACL.MAXMEANVARRATIO=47;  FEATURE.P_ACL.NAME{47}='RATIO_OF_MAX_VAR_MEAN_VAR_AXIS';
FEATURE.P_ACL.MAXMEDIANVARRATIO=48;  FEATURE.P_ACL.NAME{48}='RATIO_OF_MAX_VAR_MEDIAN_VAR_AXIS';

FEATURE.P_ACL.MAXVAR=49;      FEATURE.P_ACL.NAME{49}='MAX_VARIANCE_OVER_3AXIS';
FEATURE.P_ACL.MINVAR=50;      FEATURE.P_ACL.NAME{50}='MIN_VARIANCE_OVER_3AXIS';
FEATURE.P_ACL.MEANVAR=51;     FEATURE.P_ACL.NAME{51}='MEAN_VARIANCE_OVER_3AXIS';

FEATURE.P_ACL.AVGMAGNITUDE=52; FEATURE.P_ACL.NAME{52}='AVG_MAGNITUDE';

%FEATURE.P_ACL.AUTOCORRX=58;   FEATURE.CHESTACCE.NAME{58}='AUTOCORRELATION_X';
%FEATURE.P_ACL.AUTOCORRY=59;    FEATURE.P_ACL.NAME{59}='AUTOCORRELATION_Y';
%FEATURE.P_ACL.AUTOCORRZ=60;    FEATURE.P_ACL.NAME{60}='AUTOCORRELATION_Z';

FEATURE.P_ACL.FEATURENO=52;
%{
FEATURE.CHESTACCEL.CLASSIFIER=[
FEATURE.CHESTACCEL.MEANX,FEATURE.CHESTACCEL.MEDIANX,FEATURE.CHESTACCEL.VARIANCEX,...
FEATURE.CHESTACCEL.STDDEVX,FEATURE.CHESTACCEL.AVGFDX,FEATURE.CHESTACCEL.MEANY,...
FEATURE.CHESTACCEL.MEDIANY, FEATURE.CHESTACCEL.VARIANCEY,...
FEATURE.CHESTACCEL.STDDEVY,FEATURE.CHESTACCEL.AVGFDY,FEATURE.CHESTACCEL.MEANZ,...
FEATURE.CHESTACCEL.MEDIANZ,FEATURE.CHESTACCEL.VARIANCEZ,FEATURE.CHESTACCEL.STDDEVZ,...
FEATURE.CHESTACCEL.AVGFDZ,FEATURE.CHESTACCEL.AVGDIFFXY,FEATURE.CHESTACCEL.AVGDIFFYZ,...
FEATURE.CHESTACCEL.AVGDIFFZX,FEATURE.CHESTACCEL.MEANCROSSINGX,...
FEATURE.CHESTACCEL.MEANCROSSINGY,FEATURE.CHESTACCEL.MEANCROSSINGZ,...
FEATURE.CHESTACCEL.AVGRATIOXY,FEATURE.CHESTACCEL.AVGRATIOYZ,...
FEATURE.CHESTACCEL.AVGRATIOZX,FEATURE.CHESTACCEL.AVGENERGY,...
FEATURE.CHESTACCEL.RANGEX,FEATURE.CHESTACCEL.RANGEY,FEATURE.CHESTACCEL.RANGEZ,FEATURE.CHESTACCEL.MAGNITUDE,...
FEATURE.CHESTACCEL.STDEVMAGNITUDE,FEATURE.CHESTACCEL.HIGHFREQX,FEATURE.CHESTACCEL.HIGHFREQY,...
FEATURE.CHESTACCEL.HIGHFREQZ,FEATURE.CHESTACCEL.ENERGYX,FEATURE.CHESTACCEL.ENERGYY,FEATURE.CHESTACCEL.ENERGYZ,...
FEATURE.CHESTACCEL.MEDIANENERGYX,FEATURE.CHESTACCEL.MEDIANENERGYY,FEATURE.CHESTACCEL.MEDIANENERGYZ,...
FEATURE.CHESTACCEL.STDEVENERGYX,FEATURE.CHESTACCEL.STDEVENERGYY,FEATURE.CHESTACCEL.STDEVENERGYZ,...
FEATURE.CHESTACCEL.LOWFREQX,FEATURE.CHESTACCEL.LOWFREQY,FEATURE.CHESTACCEL.LOWFREQZ,...
FEATURE.CHESTACCEL.MAGNITUDEFFTONEHZ,FEATURE.CHESTACCEL.MAGNITUDEFFTTWOHZ,FEATURE.CHESTACCEL.MAGNITUDEFFTTHREEHZ,...
FEATURE.CHESTACCEL.MAGNITUDEFFTFOURHZ,FEATURE.CHESTACCEL.MAGNITUDEFFTFIVEHZ,FEATURE.CHESTACCEL.MAGNITUDEFFTHF,FEATURE.CHESTACCEL.MAGNITUDEFFTLF,...
FEATURE.CHESTACCEL.MAXMINVARRATIO,FEATURE.CHESTACCEL.MAXMEANVARRATIO,FEATURE.CHESTACCEL.MAXMEDIANVARRATIO
%}