function [fitresult, gof] = recovery(x, y,debug)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'recovery' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Sep-2013 23:38:08


%% Fit: 'recovery'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'b0+b1*exp(x/tau2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-1000000 -1000000 0.5];
opts.StartPoint = [0.239952525664903 0.41726706908437 0];
opts.Upper = [1000000 1000000 1000000];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
if debug==1

figure( 'Name', 'recovery' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'recovery', 'Location', 'NorthEast' );
title(['Recovery: tau=' num2str(fitresult.tau2) ' r2=' num2str(gof.rsquare) ]);

% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on
end
