function [fitresult, gof] = recovery(x, y,b0,debug)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'recovery' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Sep-2013 20:40:57


%% Fit: 'recovery'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype([num2str(b0*2) '/(1+exp(-x/tau1))-' num2str(b0)], 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = 0.0001;
opts.StartPoint = 0.1;
opts.Upper = 100000;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
if debug==1
figure( 'Name', 'recovery' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'recovery', 'Location', 'NorthEast' );
title(['Recovery: tau=' num2str(fitresult.tau1) ' r2=' num2str(gof.rsquare) ]);

% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on
end

