function [fitresult, gof] = activity_recovery(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'activity_recovery' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Sep-2013 15:12:34


%% Fit: 'activity_recovery'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'b0+b1*exp(-x/tau1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.849129305868777 0.933993247757551 0.678735154857773];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

%figure( 'Name', 'activity_recovery' );
%h = plot( fitresult, xData, yData );
%title([' tau1=' num2str(fitresult.tau1) ' r2=' num2str(gof.rsquare) ]);
%legend( h, 'y vs. x', 'activity_recovery', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'x' );
%ylabel( 'y' );
%grid on


