%% Self Report information
function SELFREPORT=config_selfreport()
SELFREPORT.DRNKID=1; SELFREPORT.ID(SELFREPORT.DRNKID).NAME='drinking';    SELFREPORT.ID(SELFREPORT.DRNKID).DB_TABLE='model21';
SELFREPORT.SMKID=2;  SELFREPORT.ID(SELFREPORT.SMKID).NAME='smoking';      SELFREPORT.ID(SELFREPORT.SMKID).DB_TABLE='model22';
SELFREPORT.CRVID=3;  SELFREPORT.ID(SELFREPORT.CRVID).NAME='craving';      SELFREPORT.ID(SELFREPORT.CRVID).DB_TABLE='model23';
end
